version: '3.8'
services:
  head-restart:
    container_name: head-restart-salesite
    restart: unless-stopped
    ports:
      - '9076:80'
    networks:
      - salesite
    build:
      context: .
      dockerfile: ./Dockerfile

networks:
  salesite:
    external: true
